const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='wde_gemini_settings_v1',HISTORY='wde_history_v3';
const MODELS={'gemini-3.5-flash-lite':'Gemini 3.5 Flash-Lite','gemini-3.6-flash':'Gemini 3.6 Flash','gemini-3.7-flash':'Gemini 3.7 Flash'};
let state={cancelled:false,current:null};
const defaults={apiKey:'',model:'gemini-3.6-flash',saveKey:true};
function settings(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return {...defaults}}}
function saveSettingsData(s){localStorage.setItem(STORE,JSON.stringify(s))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
$$('.nav-button').forEach(b=>b.onclick=()=>{showView(b.dataset.view);if(b.dataset.view==='history')renderHistory();if(b.dataset.view==='settings')loadSettings()});
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('wde_theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('wde_theme')==='dark')document.body.classList.add('dark');
function loadSettings(){const s=settings();$('#apiKey').value=s.apiKey;$('#saveKey').checked=s.saveKey;const r=document.querySelector(`input[name=model][value="${s.model}"]`)||document.querySelector('input[name=model][value="gemini-3.6-flash"]');if(r)r.checked=true}
$('#showKey').onclick=()=>{$('#apiKey').type=$('#apiKey').type==='password'?'text':'password';$('#showKey').textContent=$('#apiKey').type==='password'?'表示':'隠す'};
$('#saveSettings').onclick=()=>{const m=document.querySelector('input[name=model]:checked')?.value||defaults.model;const s={apiKey:$('#saveKey').checked?$('#apiKey').value.trim():'',model:m,saveKey:$('#saveKey').checked};saveSettingsData(s);$('#settingsStatus').textContent=`設定を保存しました。${MODELS[m]}を使用します。`;toast('Gemini設定を保存しました')};loadSettings();
$('#scanForm').onsubmit=async e=>{e.preventDefault();let raw=$('#urlInput').value.trim();if(!/^https?:\/\//i.test(raw))raw='https://'+raw;let u;try{u=new URL(raw)}catch{$('#urlInput').focus();toast('正しいURLを入力してください');return}if(!['http:','https:'].includes(u.protocol)){toast('HTTPまたはHTTPSのURLを入力してください');return}if(!settings().apiKey){$('#setupHint').classList.remove('hidden');showView('settings');toast('先にGemini APIキーを設定してください');return}$('#setupHint').classList.add('hidden');startScan(u.href)};
const steps=['仮想ブラウザでページを描画','デスクトップ・スマホ画面を取得','HTML・DOM構造を解析','SEO・UI/UX・アクセシビリティを確認','パフォーマンス・セキュリティを確認','Geminiが画面と構造を総合診断','レポートを生成'];
function startScan(url){state.cancelled=false;$('#progressUrl').textContent=url;$('#progressSteps').innerHTML=steps.map((x,i)=>`<div class="progress-step" data-step="${i}"><i class="dot"></i><span>${x}</span></div>`).join('');showView('progress');runScan(url).catch(err=>{console.error(err);if(!state.cancelled){toast(err.message||'調査に失敗しました');showView('home')}})}
function step(i){$('#progressBar').style.width=Math.min(100,Math.round((i+1)/steps.length*100))+'%';$$('.progress-step').forEach((e,n)=>e.classList.toggle('active',n<=i))}
$('#cancelScan').onclick=()=>{state.cancelled=true;showView('home');toast('調査をキャンセルしました')};
async function fetchPage(url){const r=await fetch(`https://r.jina.ai/${url}`,{headers:{Accept:'text/html'}});if(!r.ok)throw new Error(`ページ情報の取得に失敗しました (${r.status})`);const t=await r.text();if(t.length<100)throw new Error('ページ情報を十分に取得できませんでした');return t}
function screenshotUrl(url,width){return `https://image.thum.io/get/width/${width}/crop/7000/png/${url}`}
function waitImage(url){return new Promise(resolve=>{const i=new Image();let done=false;const f=v=>{if(done)return;done=true;resolve(v)};i.onload=()=>f(true);i.onerror=()=>f(false);i.src=url;setTimeout(()=>f(false),18000)})}
function parsePage(html,url){const doc=new DOMParser().parseFromString(html,'text/html');const text=(doc.body?.innerText||'').replace(/\s+/g,' ').trim();const links=[...doc.querySelectorAll('a[href]')].map(a=>({text:(a.innerText||a.getAttribute('aria-label')||'').trim().slice(0,100),href:a.href}));const images=[...doc.images].map(i=>({src:i.src,alt:i.alt||'',width:i.width,height:i.height,loading:i.loading||''}));const headings=[...doc.querySelectorAll('h1,h2,h3,h4,h5,h6')].map(h=>({tag:h.tagName,text:h.innerText.trim().slice(0,160)}));const forms=[...doc.forms].map(f=>({action:f.action,method:f.method,inputs:[...f.querySelectorAll('input,textarea,select,button')].map(x=>({tag:x.tagName,type:x.type||'',name:x.name||'',label:x.getAttribute('aria-label')||'',required:x.required}))}));const scripts=[...doc.scripts].map(s=>s.src||'inline').filter(Boolean);const styles=[...doc.querySelectorAll('link[rel=stylesheet],style')].map(x=>x.href||'inline');const meta=n=>doc.querySelector(`meta[name="${n}"]`)?.content||'';const canonical=doc.querySelector('link[rel=canonical]')?.href||'';const h1=headings.filter(h=>h.tag==='H1');const missingAlt=images.filter(i=>!i.alt).length;const emptyLinks=links.filter(l=>!l.text).length;const buttons=[...doc.querySelectorAll('button,input[type=button],input[type=submit]')];const unlabeledButtons=buttons.filter(b=>!(b.innerText||b.value||b.getAttribute('aria-label')||b.title).trim()).length;const inputs=[...doc.querySelectorAll('input,textarea,select')];const formsNoLabels=inputs.filter(x=>!x.getAttribute('aria-label')&&!x.id&&!x.name).length;const insecureForms=[...doc.forms].filter(f=>/^http:/i.test(f.action)).length;const origin=new URL(url).origin;const internal=links.filter(l=>{try{return new URL(l.href,url).origin===origin}catch{return false}});return {url,title:doc.title||'',description:meta('description'),viewport:doc.querySelector('meta[name=viewport]')?.content||'',lang:doc.documentElement.lang||'',canonical,charset:doc.characterSet,bodyText:text.slice(0,16000),stats:{htmlBytes:html.length,links:links.length,internalLinks:internal.length,externalLinks:links.length-internal.length,images:images.length,missingAlt,headings:headings.length,h1:h1.length,forms:forms.length,scripts:scripts.length,styles:styles.length,emptyLinks,unlabeledButtons,formsNoLabels,insecureForms},headings:headings.slice(0,80),links:links.slice(0,120),images:images.slice(0,100),forms:forms.slice(0,30),scripts:scripts.slice(0,100),styles:styles.slice(0,100)}}
function localFindings(d){const f=[];const add=(severity,title,description,recommendation,category)=>f.push({severity,title,description,recommendation,category});if(!d.title)add('high','ページタイトルがありません','ブラウザや検索結果でページ内容を判断しにくくなります。','内容を表すtitleを設定してください。','SEO');if(!d.description)add('medium','メタディスクリプションがありません','検索結果でページ概要が適切に伝わらない可能性があります。','内容を要約したdescriptionを設定してください。','SEO');if(!d.viewport)add('high','モバイル用viewportがありません','スマートフォンで意図した表示にならない可能性があります。','width=device-width, initial-scale=1を設定してください。','レスポンシブ');if(!d.stats.h1)add('medium','H1見出しがありません','ページの主題を機械的に把握しにくくなる可能性があります。','ページの主題を表すH1を設けてください。','SEO');if(d.stats.missingAlt)add('medium',`代替テキストのない画像が${d.stats.missingAlt}件あります`,'画像の内容が読み上げ環境などで伝わらない可能性があります。','意味のある画像にaltを追加してください。','アクセシビリティ');if(d.stats.unlabeledButtons)add('high',`名前のないボタンが${d.stats.unlabeledButtons}件あります`,'ボタンの目的を判断しにくい可能性があります。','ボタンテキストまたはaria-labelを追加してください。','アクセシビリティ');if(d.stats.formsNoLabels)add('medium',`ラベルが明確でない入力欄が${d.stats.formsNoLabels}件あります`,'入力内容を支援技術が判断しにくい可能性があります。','labelまたはaria-labelを設定してください。','アクセシビリティ');if(d.stats.images>25)add('low',`画像が${d.stats.images}件あります`,'画像数が多いページでは転送量や描画負荷が増える可能性があります。','画像圧縮や遅延読み込みを検討してください。','パフォーマンス');if(d.stats.scripts>25)add('low',`スクリプトが${d.stats.scripts}件あります`,'JavaScriptの読み込み量が初期表示に影響する可能性があります。','不要なスクリプトを削減してください。','パフォーマンス');if(d.stats.insecureForms)add('high','HTTP送信のフォームがあります','暗号化されない送信先へ入力内容が送られる可能性があります。','HTTPSの送信先へ変更してください。','セキュリティ');return f}
async function imagePart(url){const r=await fetch(url);if(!r.ok)throw new Error('スクリーンショットを取得できませんでした');const b=await r.blob();const bytes=new Uint8Array(await b.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return {inline_data:{mime_type:b.type||'image/png',data:btoa(binary)}}}
async function askGemini(data,findings,shots){const s=settings();const prompt=`あなたはWebサイト監査の専門家です。日本語で詳細に診断してください。対象ページのデスクトップとスマホの実際のスクリーンショットを入力しています。スクリーンショットからUI、UX、レイアウト、視覚的階層、余白、文字サイズ、CTA、ナビゲーション、情報密度、レスポンシブ表示を観察し、DOMデータと照合してください。DOMだけからUIを推測しないでください。SEO、アクセシビリティ、パフォーマンス、セキュリティも確認してください。確認できない脆弱性は断定せず、セキュリティは外部から確認可能な設定・兆候の範囲で評価してください。良い点も必ず挙げてください。JSONのみで返してください。形式: {"summary":"総評","scores":{"uiux":0,"seo":0,"accessibility":0,"performance":0,"security":0},"strengths":["良い点"],"findings":[{"severity":"high|medium|low","title":"問題","description":"分かりやすい説明","recommendation":"具体的な改善案","category":"UI/UX|SEO|アクセシビリティ|パフォーマンス|セキュリティ|レスポンシブ|コンテンツ"}]}. スコアは0-100。highは本当に重要なものだけ。\nDOM検査データ:\n${JSON.stringify(data).slice(0,50000)}\n機械的検出:\n${JSON.stringify(findings).slice(0,15000)}`;const parts=[{text:prompt},await imagePart(shots.desktop),await imagePart(shots.mobile)];const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(s.model)}:generateContent?key=${encodeURIComponent(s.apiKey)}`;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{responseMimeType:'application/json',maxOutputTokens:6000}})});if(!r.ok){const t=await r.text();throw new Error(`Gemini診断に失敗しました (${r.status}) ${t.slice(0,180)}`)}const j=await r.json();const text=j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';if(!text)throw new Error('Geminiから診断結果を取得できませんでした');return JSON.parse(text.replace(/^```json\s*/,'').replace(/\s*```$/,'').trim())}
async function runScan(url){step(0);const shots={desktop:screenshotUrl(url,1440),mobile:screenshotUrl(url,390)};const availability=await Promise.all([waitImage(shots.desktop),waitImage(shots.mobile)]);if(state.cancelled)return;if(!availability[0]&&!availability[1])throw new Error('仮想ブラウザでページを描画できませんでした');step(1);const html=await fetchPage(url);if(state.cancelled)return;step(2);const data=parsePage(html,url);data.renderedView={desktop:shots.desktop,mobile:shots.mobile,desktopAvailable:availability[0],mobileAvailable:availability[1]};step(3);const local=localFindings(data);step(4);step(5);const ai=await askGemini(data,local,shots);if(state.cancelled)return;step(6);const merged=[...local,...(ai.findings||[])].filter((x,i,a)=>i===a.findIndex(y=>y.title===x.title));const sc=ai.scores||{};const vals=['uiux','seo','accessibility','performance','security'].map(k=>Math.max(0,Math.min(100,Number(sc[k]??70))));const report={url,data,ai:{...ai,scores:{uiux:vals[0],seo:vals[1],accessibility:vals[2],performance:vals[3],security:vals[4]}},findings:merged,overall:Math.round(vals.reduce((a,b)=>a+b,0)/5),model:settings().model,date:new Date().toISOString()};state.current=report;saveHistory(report);renderReport(report);showView('results')}
function saveHistory(r){const h=JSON.parse(localStorage.getItem(HISTORY)||'[]');h.unshift(r);localStorage.setItem(HISTORY,JSON.stringify(h.slice(0,20)))}
function renderHistory(){const h=JSON.parse(localStorage.getItem(HISTORY)||'[]');$('#historyList').innerHTML=h.length?h.map((r,i)=>`<article class="history-item"><div><b>${escapeHtml(r.data?.title||r.url)}</b><small>${new Date(r.date).toLocaleString('ja-JP')} · ${MODELS[r.model]||r.model}</small></div><strong>${r.overall}</strong><button class="mini-button" data-history="${i}">開く</button></article>`).join(''):'<div class="empty-state">まだ検査履歴がありません。</div>';$$('[data-history]').forEach(b=>b.onclick=()=>{const r=h[Number(b.dataset.history)];if(r){state.current=r;renderReport(r);showView('results')}})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderReport(r){$('#reportTitle').textContent=r.data?.title||'診断レポート';$('#reportUrl').textContent=r.url;$('#reportUrl').href=r.url;$('#overallScore').textContent=r.overall;$('#scoreSummary').textContent=r.ai?.summary||'';const counts={high:0,medium:0,low:0};(r.findings||[]).forEach(f=>counts[f.severity]=(counts[f.severity]||0)+1);$('#findingSummary').textContent=`重要 ${counts.high||0}件 · 要改善 ${counts.medium||0}件 · 軽微 ${counts.low||0}件`;$('#findingCount').textContent=`${r.findings?.length||0}件`;$('#findings').innerHTML=(r.findings||[]).map(f=>`<article class="finding ${escapeHtml(f.severity)}"><div class="finding-top"><span class="severity">${escapeHtml(f.severity)}</span><b>${escapeHtml(f.title)}</b><small>${escapeHtml(f.category||'')}</small></div><p>${escapeHtml(f.description||'')}</p><div class="recommendation"><b>改善案</b><p>${escapeHtml(f.recommendation||'')}</p></div></article>`).join('')||'<div class="empty-state">大きな問題は検出されませんでした。</div>';const d=r.data||{},s=d.stats||{};$('#siteFacts').innerHTML=[['URL',r.url],['タイトル',d.title||'なし'],['H1',s.h1??0],['リンク',s.links??0],['画像',s.images??0],['スクリプト',s.scripts??0],['フォーム',s.forms??0]].map(x=>`<div><span>${escapeHtml(x[0])}</span><b>${escapeHtml(x[1])}</b></div>`).join('');const sc=r.ai?.scores||{};$('#categoryScores').innerHTML=[['UI/UX',sc.uiux],['SEO',sc.seo],['アクセシビリティ',sc.accessibility],['パフォーマンス',sc.performance],['セキュリティ',sc.security]].map(x=>`<div class="category-score"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#strengths').innerHTML=(r.ai?.strengths||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>特になし</li>';$('#desktopShot').src=d.renderedView?.desktop||'';$('#mobileShot').src=d.renderedView?.mobile||'';$('#technicalData').textContent=JSON.stringify({model:r.model,url:r.url,stats:d.stats,headings:d.headings,canonical:d.canonical,viewport:d.viewport},null,2)}
$('#toggleTechnical').onclick=()=>{$('#technicalData').classList.toggle('hidden');$('#toggleTechnical').textContent=$('#technicalData').classList.contains('hidden')?'表示':'隠す'};
$('#copyReport').onclick=async()=>{const r=state.current;if(!r)return;const text=[`Web Detailed Examination`,`URL: ${r.url}`,`総合スコア: ${r.overall}/100`,`\n${r.ai?.summary||''}`,`\n問題と改善提案`,...(r.findings||[]).map(f=>`[${f.severity}] ${f.title}\n${f.description}\n改善案: ${f.recommendation}`),`\n良かったところ`,...(r.ai?.strengths||[]).map(x=>`- ${x}`)].join('\n');await navigator.clipboard.writeText(text);toast('レポートをコピーしました')};
$('#newScan').onclick=()=>showView('home');
