const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='wde_gemini_settings_v1',HISTORY='wde_history_v3';
const MODELS={'gemini-3.5-flash-lite':'Gemini 3.5 Flash-Lite','gemini-3.6-flash':'Gemini 3.6 Flash','gemini-3.7-flash':'Gemini 3.7 Flash'};
let state={cancelled:false,current:null};
const defaults={apiKey:'',model:'gemini-3.6-flash',saveKey:true};
function settings(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return {...defaults}}}
function saveSettingsData(s){localStorage.setItem(STORE,JSON.stringify(s))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
$$('.nav-button').forEach(b=>b.onclick=()=>{showView(b.dataset.view);if(b.dataset.view==='history')renderHistory();if(b.dataset.view==='settings')loadSettings()});
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('wde_theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('wde_theme')==='dark')document.body.classList.add('dark');
function loadSettings(){const s=settings();$('#apiKey').value=s.apiKey;$('#saveKey').checked=s.saveKey;const r=document.querySelector(`input[name=model][value="${s.model}"]`)||document.querySelector('input[name=model][value="gemini-3.6-flash"]');if(r)r.checked=true}
$('#showKey').onclick=()=>{$('#apiKey').type=$('#apiKey').type==='password'?'text':'password';$('#showKey').textContent=$('#apiKey').type==='password'?'表示':'隠す'};
$('#saveSettings').onclick=()=>{const m=document.querySelector('input[name=model]:checked')?.value||defaults.model;const s={apiKey:$('#saveKey').checked?$('#apiKey').value.trim():'',model:m,saveKey:$('#saveKey').checked};saveSettingsData(s);$('#settingsStatus').textContent=`設定を保存しました。${MODELS[m]}を使用します。`;toast('Gemini設定を保存しました')};loadSettings();
$('#scanForm').onsubmit=async e=>{e.preventDefault();let raw=$('#urlInput').value.trim();if(!/^https?:\/\//i.test(raw))raw='https://'+raw;let u;try{u=new URL(raw)}catch{$('#urlInput').focus();toast('正しいURLを入力してください');return}if(!['http:','https:'].includes(u.protocol)){toast('HTTPまたはHTTPSのURLを入力してください');return}if(!settings().apiKey){$('#setupHint').classList.remove('hidden');showView('settings');toast('先にGemini APIキーを設定してください');return}$('#setupHint').classList.add('hidden');startScan(u.href)};
const steps=['仮想ブラウザでページを描画','デスクトップ・スマホ画面を取得','HTML・DOM構造を解析','SEO・UI/UX・アクセシビリティを確認','パフォーマンス・セキュリティを確認','Geminiが画面と構造を総合診断','レポートを生成'];
function startScan(url){state.cancelled=false;$('#progressUrl').textContent=url;$('#progressSteps').innerHTML=steps.map((x,i)=>`<div class="progress-step" data-step="${i}"><i class="dot"></i><span>${x}</span></div>`).join('');showView('progress');runScan(url).catch(err=>{console.error(err);if(!state.cancelled){toast(err.message||'調査に失敗しました');showView('home')}})}
function step(i){$('#progressBar').style.width=Math.min(100,Math.round((i+1)/steps.length*100))+'%';$$('.progress-step').forEach((e,n)=>e.classList.toggle('active',n<=i))}
$('#cancelScan').onclick=()=>{state.cancelled=true;showView('home');toast('調査をキャンセルしました')};
async function fetchPage(url){const r=await fetch(`https://r.jina.ai/${url}`,{headers:{Accept:'text/html'}});if(!r.ok)throw new Error(`ページ情報の取得に失敗しました (${r.status})`);const t=await r.text();if(t.length<100)throw new Error('ページ情報を十分に取得できませんでした');return t}
function screenshotUrl(url,width){return `https://image.thum.io/get/width/${width}/crop/7000/png/${url}`}
function waitImage(url){return new Promise(resolve=>{const i=new Image();let done=false;const f=v=>{if(done)return;done=true;resolve(v)};i.onload=()=>f(true);i.onerror=()=>f(false);i.src=url;setTimeout(()=>f(false),18000)})}
function parsePage(html,url){const doc=new DOMParser().parseFromString(html,'text/html');const text=(doc.body?.innerText||'').replace(/\s+/g,' ').trim();const links=[...doc.querySelectorAll('a[href]')].map(a=>({text:(a.innerText||a.getAttribute('aria-label')||'').trim().slice(0,100),href:a.href}));const images=[...doc.images].map(i=>({src:i.src,alt:i.alt||'',width:i.width,height:i.height,loading:i.loading||''}));const headings=[...doc.querySelectorAll('h1,h2,h3,h4,h5,h6')].map(h=>({tag:h.tagName,text:h.innerText.trim().slice(0,160)}));const forms=[...doc.forms].map(f=>({action:f.action,method:f.method,inputs:[...f.querySelectorAll('input,textarea,select,button')].map(x=>({tag:x.tagName,type:x.type||'',name:x.name||'',label:x.getAttribute('aria-label')||'',required:x.required}))}));const scripts=[...doc.scripts].map(s=>s.src||'inline').filter(Boolean);const styles=[...doc.querySelectorAll('link[rel=stylesheet],style')].map(x=>x.href||'inline');const meta=n=>doc.querySelector(`meta[name="${n}"]`)?.content||'';const canonical=doc.querySelector('link[rel=canonical]')?.href||'';const h1=headings.filter(h=>h.tag==='H1');const missingAlt=images.filter(i=>!i.alt).length;const emptyLinks=links.filter(l=>!l.text).length;const buttons=[...doc.querySelectorAll('button,input[type=button],input[type=submit]')];const unlabeledButtons=buttons.filter(b=>!(b.innerText||b.value||b.getAttribute('aria-label')||b.title).trim()).length;const inputs=[...doc.querySelectorAll('input,textarea,select')];const formsNoLabels=inputs.filter(x=>!x.getAttribute('aria-label')&&!x.id&&!x.name).length;const insecureForms=[...doc.forms].filter(f=>/^http:/i.test(f.action)).length;const origin=new URL(url).origin;const internal=links.filter(l=>{try{return new URL(l.href,url).origin===origin}catch{return false}});return {url,title:doc.title||'',description:meta('description'),viewport:doc.querySelector('meta[name=viewport]')?.content||'',lang:doc.documentElement.lang||'',canonical,charset:doc.characterSet,bodyText:text.slice(0,16000),stats:{htmlBytes:html.length,links:links.length,internalLinks:internal.length,externalLinks:links.length-internal.length,images:images.length,missingAlt,headings:headings.length,h1:h1.length,forms:forms.length,scripts:scripts.length,styles:styles.length,emptyLinks,unlabeledButtons,formsNoLabels,insecureForms},headings:headings.slice(0,80),links:links.slice(0,120),images:images.slice(0,100),forms:forms.slice(0,30),scripts:scripts.slice(0,100),styles:styles.slice(0,100)}}
function localFindings(d){const f=[];const add=(severity,title,description,recommendation,category)=>f.push({severity,title,description,recommendation,category});if(!d.title)add('high','ページタイトルがありません','ブラウザや検索結果でページ内容を判断しにくくなります。','内容を表すtitleを設定してください。','SEO');if(!d.description)add('medium','メタディスクリプションがありません','検索結果でページ概要が適切に伝わらない可能性があります。','内容を要約したdescriptionを設定してください。','SEO');if(!d.viewport)add('high','モバイル用viewportがありません','スマートフォンで意図した表示にならない可能性があります。','width=device-width, initial-scale=1を設定してください。','レスポンシブ');if(!d.stats.h1)add('medium','H1見出しがありません','ページの主題を機械的に把握しにくくなる可能性があります。','ページの主題を表すH1を設けてください。','SEO');if(d.stats.missingAlt)add('medium',`代替テキストのない画像が${d.stats.missingAlt}件あります`,'画像の内容が読み上げ環境などで伝わらない可能性があります。','意味のある画像にaltを追加してください。','アクセシビリティ');if(d.stats.unlabeledButtons)add('high',`名前のないボタンが${d.stats.unlabeledButtons}件あります`,'ボタンの目的を判断しにくい可能性があります。','ボタンテキストまたはaria-labelを追加してください。','アクセシビリティ');if(d.stats.formsNoLabels)add('medium',`ラベルが明確でない入力欄が${d.stats.formsNoLabels}件あります`,'入力内容を支援技術が判断しにくい可能性があります。','labelまたはaria-labelを設定してください。','アクセシビリティ');if(d.stats.images>25)add('low',`画像が${d.stats.images}件あります`,'画像数が多いページでは転送量や描画負荷が増える可能性があります。','画像圧縮や遅延読み込みを検討してください。','パフォーマンス');if(d.stats.scripts>25)add('low',`スクリプトが${d.stats.scripts}件あります`,'JavaScriptの読み込み量が初期表示に影響する可能性があります。','不要なスクリプトを削減してください。','パフォーマンス');if(d.stats.insecureForms)add('high','HTTP送信のフォームがあります','暗号化されない送信先へ入力内容が送られる可能性があります。','HTTPSの送信先へ変更してください。','セキュリティ');return f}
async function imagePart(url){const r=await fetch(url);if(!r.ok)throw new Error('スクリーンショットを取得できませんでした');const b=await r.blob();const bytes=new Uint8Array(await b.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return {inline_data:{mime_type:b.type||'image/png',data:btoa(binary)}}}
async function askGemini(data,findings,shots){const s=settings();const prompt=`あなたはWebサイト監査の専門家です。日本語で詳細に診断してください。対象ページのデスクトップとスマホの実際のスクリーンショットを入力しています。スクリーンショットからUI、UX、レイアウト、視覚的階層、余白、文字サイズ、CTA、ナビゲーション、情報密度、レスポンシブ表示を観察し、DOMデータと照合してください。DOMだけからUIを推測しないでください。SEO、アクセシビリティ、パフォーマンス、セキュリティも確認してください。確認できない脆弱性は断定せず、セキュリティは外部から確認可能な設定・兆候の範囲で評価してください。良い点も必ず挙げてください。JSONのみで返してください。形式: {"summary":"総評","scores":{"uiux":0,"seo":0,"accessibility":0,"performance":0,"security":0},"strengths":["良い点"],"findings":[{"severity":"high|medium|low","title":"問題","description":"分かりやすい説明","recommendation":"具体的な改善案","category":"UI/UX|SEO|アクセシビリティ|パフォーマンス|セキュリティ|レスポンシブ|コンテンツ"}]}. スコアは0-100。highは本当に重要なものだけ。\nDOM検査データ:\n${JSON.stringify(data).slice(0,50000)}\n機械的検出:\n${JSON.stringify(findings).slice(0,15000)}`;const parts=[{text:prompt},await imagePart(shots.desktop),await imagePart(shots.mobile)];const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(s.model)}:generateContent?key=${encodeURIComponent(s.apiKey)}`;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{responseMimeType:'application/json',maxOutputTokens:6000}})});if(!r.ok){const t=await r.text();throw new Error(`Gemini診断に失敗しました (${r.status}) ${t.slice(0,180)}`)}const j=await r.json();const text=j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';if(!text)throw new Error('Geminiから診断結果を取得できませんでした');return JSON.parse(text.replace(/^```json\s*/,'').replace(/\s*```$/,'').trim())}
async function runScan(url){step(0);const shots={desktop:screenshotUrl(url,1440),mobile:screenshotUrl(url,390)};const availability=await Promise.all([waitImage(shots.desktop),waitImage(shots.mobile)]);if(state.cancelled)return;if(!availability[0]&&!availability[1])throw new Error('仮想ブラウザでページを描画できませんでした');step(1);const html=await fetchPage(url);if(state.cancelled)return;step(2);const data=parsePage(html,url);data.renderedView={desktop:shots.desktop,mobile:shots.mobile,desktopAvailable:availability[0],mobileAvailable:availability[1]};step(3);const local=localFindings(data);step(4);step(5);const ai=await askGemini(data,local,shots);if(state.cancelled)return;step(6);const merged=[...local,...(ai.findings||[])].filter((x,i,a)=>i===a.findIndex(y=>y.title===x.title));const sc=ai.scores||{};const vals=['uiux','seo','accessibility','performance','security'].map(k=>Math.max(0,Math.min(100,Number(sc[k]??70))));const report={url,data,ai:{...ai,scores:{uiux:vals[0],seo:vals[1],accessibility:vals[2],performance:vals[3],security:vals[4]}},findings:merged,overall:Math.round(vals.reduce((a,b)=>a+b,0)/5),model:settings().model,date:new Date().toISOString()};state.current=report;saveHistory(report);renderReport(report);showView('results')}
function saveHistory(r){let h=[];try{h=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{};h=[r,...h.filter(x=>x.url!==r.url)].slice(0,20);localStorage.setItem(HISTORY,JSON.stringify(h))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderReport(r){$('#reportTitle').textContent=r.data.title||new URL(r.url).hostname;$('#reportUrl').textContent=r.url;$('#reportUrl').href=r.url;$('#overallScore').textContent=r.overall;const names=[['uiux','UI/UX'],['seo','SEO'],['accessibility','アクセシビリティ'],['performance','パフォーマンス'],['security','安全性']];$('#scoreSummary').innerHTML=names.map(([k,n])=>`<div class="score-item"><span>${n}</span><b>${r.ai.scores[k]}</b><div class="score-line"><i style="width:${r.ai.scores[k]}%"></i></div></div>`).join('');const c={high:r.findings.filter(f=>f.severity==='high').length,medium:r.findings.filter(f=>f.severity==='medium').length,low:r.findings.filter(f=>f.severity==='low').length};$('#findingSummary').innerHTML=`<span class="pill">重大 ${c.high}</span><span class="pill">注意 ${c.medium}</span><span class="pill">提案 ${c.low}</span><span class="pill">${r.findings.length}件の指摘</span>`;$('#findingCount').textContent=`${r.findings.length}件`;$('#findings').innerHTML=r.findings.map(f=>`<article class="finding"><div class="finding-top"><span class="severity ${f.severity}">${f.severity==='high'?'重大':f.severity==='medium'?'注意':'提案'}</span><span class="severity">${esc(f.category||'総合')}</span></div><h4>${esc(f.title)}</h4><p>${esc(f.description)}</p><p class="recommend"><b>改善案:</b> ${esc(f.recommendation)}</p></article>`).join('')||'<p>大きな問題は検出されませんでした。</p>';const d=r.data;$('#siteFacts').innerHTML=[['タイトル',d.title||'なし'],['HTTPS',new URL(r.url).protocol==='https:'?'有効':'なし'],['リンク',d.stats.links],['画像',d.stats.images],['フォーム',d.stats.forms],['スクリプト',d.stats.scripts],['HTMLサイズ',Math.round(d.stats.htmlBytes/1024)+' KB'],['使用モデル',MODELS[r.model]||r.model]].map(x=>`<div class="fact"><span>${x[0]}</span><b>${esc(String(x[1]))}</b></div>`).join('');$('#categoryScores').innerHTML=names.map(([k,n])=>`<div class="cat"><span>${n}</span><b>${r.ai.scores[k]}/100</b></div>`).join('');$('#strengths').innerHTML=(r.ai.strengths||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>特筆事項なし</li>';$('#desktopShot').src=d.renderedView.desktop;$('#mobileShot').src=d.renderedView.mobile;$('#technicalData').textContent=JSON.stringify({URL:r.url,取得日時:r.date,モデル:MODELS[r.model],サイト情報:r.data.stats,見出し:r.data.headings,AI分析:r.ai},null,2)}
$('#newScan').onclick=()=>{showView('home');$('#urlInput').focus()};$('#toggleTechnical').onclick=()=>{$('#technicalData').classList.toggle('hidden');$('#toggleTechnical').textContent=$('#technicalData').classList.contains('hidden')?'表示':'隠す'};$('#copyReport').onclick=async()=>{const r=state.current;if(!r)return;await navigator.clipboard.writeText(`Web Detailed Examination\n${r.url}\n総合スコア: ${r.overall}/100\nモデル: ${MODELS[r.model]}\n\n${r.ai.summary||''}\n\n`+r.findings.map(f=>`[${f.severity}] ${f.title}\n${f.description}\n改善案: ${f.recommendation}`).join('\n\n'));toast('レポートをコピーしました')};
function renderHistory(){let h=[];try{h=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{};$('#historyList').innerHTML=h.length?h.map((r,i)=>`<div class="history-item" data-i="${i}"><div><b>${esc(r.data?.title||new URL(r.url).hostname)}</b><small>${esc(r.url)} · ${new Date(r.date).toLocaleString('ja-JP')} · ${esc(MODELS[r.model]||r.model||'Gemini')}</small></div><strong>${r.overall}/100</strong></div>`).join(''):'<div class="history-item"><div><b>履歴はありません</b><small>サイトを調べるとここに保存されます。</small></div></div>';$$('.history-item[data-i]').forEach(e=>e.onclick=()=>{const h=JSON.parse(localStorage.getItem(HISTORY)||'[]');state.current=h[+e.dataset.i];renderReport(state.current);showView('results')})}renderHistory();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));