const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const STORE='wde_settings_v1',HISTORY='wde_history_v1';
let state={cancelled:false,current:null};
const defaultSettings={provider:'openrouter',apiKey:'',model:'openrouter/free',saveKey:true};
function settings(){try{return {...defaultSettings,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return {...defaultSettings}}}
function saveSettingsData(s){localStorage.setItem(STORE,JSON.stringify(s))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-button').forEach(b=>b.onclick=()=>{showView(b.dataset.view);if(b.dataset.view==='history')renderHistory();if(b.dataset.view==='settings')loadSettings()});
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('wde_theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('wde_theme')==='dark')document.body.classList.add('dark');
function loadSettings(){const s=settings();$('#provider').value=s.provider;$('#apiKey').value=s.apiKey;$('#model').value=s.model;$('#saveKey').checked=s.saveKey}
$('#showKey').onclick=()=>{$('#apiKey').type=$('#apiKey').type==='password'?'text':'password';$('#showKey').textContent=$('#apiKey').type==='password'?'表示':'隠す'};
$('#saveSettings').onclick=()=>{const s={provider:$('#provider').value,apiKey:$('#saveKey').checked?$('#apiKey').value:'',model:$('#model').value,saveKey:$('#saveKey').checked};saveSettingsData(s);$('#settingsStatus').textContent='設定を保存しました。';toast('設定を保存しました')};loadSettings();
$('#scanForm').onsubmit=async e=>{e.preventDefault();let raw=$('#urlInput').value.trim();if(!/^https?:\/\//i.test(raw))raw='https://'+raw;let u;try{u=new URL(raw)}catch{$('#urlInput').focus();toast('正しいURLを入力してください');return}if(!['http:','https:'].includes(u.protocol)){toast('HTTPまたはHTTPSのURLを入力してください');return}const s=settings();if(!s.apiKey){$('#setupHint').classList.remove('hidden');showView('settings');toast('先にAPIキーを設定してください');return}$('#setupHint').classList.add('hidden');startScan(u.href)};
const steps=['ページを取得','HTML構造を解析','SEO・リンク・メディアを確認','アクセシビリティを確認','パフォーマンス要素を確認','AIによる総合診断','レポートを生成'];
function startScan(url){state.cancelled=false;$('#progressUrl').textContent=url;$('#progressSteps').innerHTML=steps.map((x,i)=>`<div class="progress-step" data-step="${i}"><i class="dot"></i><span>${x}</span></div>`).join('');showView('progress');runScan(url).catch(err=>{console.error(err);if(!state.cancelled){toast(err.message||'調査に失敗しました');showView('home')}})}
function step(i){const p=Math.min(100,Math.round((i+1)/steps.length*100));$('#progressBar').style.width=p+'%';$$('.progress-step').forEach((e,n)=>e.classList.toggle('active',n<=i))}
$('#cancelScan').onclick=()=>{state.cancelled=true;showView('home');toast('調査をキャンセルしました')};
async function fetchPage(url){const candidates=[`https://r.jina.ai/${url}`,`https://r.jina.ai/http://${url.replace(/^https?:\/\//,'')}`];let last;for(const endpoint of candidates){try{const r=await fetch(endpoint,{headers:{Accept:'text/html'}});if(r.ok){const text=await r.text();if(text.length>100)return text}last=new Error(`ページ取得失敗: ${r.status}`)}catch(e){last=e}}throw last||new Error('ページを取得できませんでした')}
function parsePage(html,url){const doc=new DOMParser().parseFromString(html,'text/html');const text=(doc.body?.innerText||'').replace(/\s+/g,' ').trim();const links=[...doc.querySelectorAll('a[href]')].map(a=>({text:(a.innerText||a.getAttribute('aria-label')||'').trim().slice(0,100),href:a.href}));const images=[...doc.images].map(i=>({src:i.src,alt:i.alt||'',width:i.naturalWidth||i.width,height:i.naturalHeight||i.height}));const headings=[...doc.querySelectorAll('h1,h2,h3,h4,h5,h6')].map(h=>({tag:h.tagName,text:h.innerText.trim().slice(0,160)}));const forms=[...doc.forms].map(f=>({action:f.action,method:f.method,inputs:[...f.querySelectorAll('input,textarea,select,button')].map(x=>({tag:x.tagName,type:x.type||'',name:x.name||'',label:x.getAttribute('aria-label')||''}))}));const scripts=[...doc.scripts].map(s=>s.src||'inline').filter(Boolean);const styles=[...doc.querySelectorAll('link[rel=stylesheet],style')].map(x=>x.href||'inline');const meta=n=>doc.querySelector(`meta[name="${n}"]`)?.content||'';const canonical=doc.querySelector('link[rel=canonical]')?.href||'';const title=doc.title||'';const h1=headings.filter(h=>h.tag==='H1');const missingAlt=images.filter(i=>!i.alt).length;const emptyLinks=links.filter(l=>!l.text).length;const buttons=[...doc.querySelectorAll('button,input[type=button],input[type=submit]')];const unlabeledButtons=buttons.filter(b=>!(b.innerText||b.value||b.getAttribute('aria-label')||b.title).trim()).length;const internal=links.filter(l=>{try{return new URL(l.href,url).origin===new URL(url).origin}catch{return false}});const external=links.length-internal.length;return {url,title,description:meta('description'),viewport:doc.querySelector('meta[name=viewport]')?.content||'',lang:doc.documentElement.lang||'',canonical,charset:doc.characterSet,bodyText:text.slice(0,12000),stats:{htmlBytes:html.length,links:links.length,internalLinks:internal.length,externalLinks:external,images:images.length,missingAlt,headings:headings.length,h1:h1.length,forms:forms.length,scripts:scripts.length,styles:styles.length,emptyLinks,unlabeledButtons},headings:headings.slice(0,60),links:links.slice(0,100),images:images.slice(0,80),forms:forms.slice(0,20),scripts:scripts.slice(0,80)} }
function localFindings(d){const f=[];const add=(severity,title,desc,recommend,cat='UI/UX')=>f.push({severity,title,description:desc,recommendation:recommend,category:cat});if(!d.title)add('high','ページタイトルがありません','ブラウザや検索結果でページの内容を判断しにくくなります。','内容を表すtitleを設定してください。','SEO');if(!d.description)add('medium','メタディスクリプションがありません','検索結果でページの概要が適切に伝わらない可能性があります。','ページ内容を要約したdescriptionを設定してください。','SEO');if(!d.viewport)add('high','モバイル用viewportがありません','スマートフォンで意図した表示にならない可能性があります。','width=device-width, initial-scale=1 を設定してください。','レスポンシブ');if(d.stats.h1===0)add('medium','H1見出しがありません','ページの主題を示す主要見出しを機械的に認識しにくくなります。','ページの主題を表すH1を1つ設けてください。','SEO');if(d.stats.h1>1)add('low','H1見出しが複数あります','複数H1が常に問題とは限りませんが、ページ構造が分かりにくくなる場合があります。','意図した構造か確認してください。','SEO');if(d.stats.missingAlt)add('medium',`代替テキストのない画像が${d.stats.missingAlt}件あります`,'画像の内容が読み上げ環境などで伝わらない可能性があります。','意味のある画像にはaltを追加し、装飾画像は空altにしてください。','アクセシビリティ');if(d.stats.emptyLinks)add('medium',`テキストのないリンクが${d.stats.emptyLinks}件あります`,'リンクの目的が利用者や支援技術から分かりにくい可能性があります。','リンクテキストまたはaria-labelを追加してください。','アクセシビリティ');if(d.stats.unlabeledButtons)add('high',`名前のないボタンが${d.stats.unlabeledButtons}件あります`,'ボタンの役割を利用者が判断できない可能性があります。','ボタンテキスト、aria-label、titleなどで目的を明確にしてください。','アクセシビリティ');if(d.stats.images>25)add('low',`画像が${d.stats.images}件あります`,'画像数が多いページでは転送量や描画負荷が大きくなる可能性があります。','不要な画像を減らし、適切な圧縮や遅延読み込みを検討してください。','パフォーマンス');if(d.stats.scripts>25)add('low',`スクリプトが${d.stats.scripts}件あります`,'JavaScriptの読み込みが多いと初期表示に影響する場合があります。','不要なスクリプトを削減し、必要に応じてdefer等を検討してください。','パフォーマンス');return f}
async function askAI(data,findings){const s=settings();const prompt=`あなたはWebサイト品質診断の専門家です。以下の検査データを日本語で分析してください。事実と推測を区別し、確認できない脆弱性を断定しないでください。専門用語は必ず平易に説明してください。JSONのみで返してください。形式: {"summary":"短い総評","scores":{"uiux":0,"seo":0,"accessibility":0,"performance":0,"security":0},"findings":[{"severity":"high|medium|low","title":"問題","description":"利用者に分かる説明","recommendation":"具体的な改善案","category":"カテゴリ"}]}。各スコアは0-100。重大度は本当に重要なものだけhighにしてください。\n検査データ:\n${JSON.stringify(data).slice(0,30000)}\nローカル検出:\n${JSON.stringify(findings)}`;const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.apiKey,'HTTP-Referer':location.origin,'X-Title':'Web Detailed Examination'},body:JSON.stringify({model:s.model,messages:[{role:'system',content:'あなたは正確で慎重なWeb監査AIです。JSON以外は出力しません。'},{role:'user',content:prompt}],temperature:.2})});if(!r.ok){const t=await r.text();throw new Error(`AI診断に失敗しました (${r.status}) ${t.slice(0,180)}`)}const j=await r.json();const content=j.choices?.[0]?.message?.content||'';const clean=content.replace(/^```json\s*/,'').replace(/\s*```$/,'').trim();return JSON.parse(clean)}
async function runScan(url){for(let i=0;i<2;i++){step(i);await new Promise(r=>setTimeout(r,250))}const html=await fetchPage(url);if(state.cancelled)return;step(2);const data=parsePage(html,url);await new Promise(r=>setTimeout(r,300));if(state.cancelled)return;step(3);const local=localFindings(data);await new Promise(r=>setTimeout(r,250));step(4);await new Promise(r=>setTimeout(r,250));step(5);const ai=await askAI(data,local);if(state.cancelled)return;step(6);const merged=[...local,...(ai.findings||[])].filter((x,i,a)=>i===a.findIndex(y=>y.title===x.title));const scores=ai.scores||{};const vals=[scores.uiux??70,scores.seo??70,scores.accessibility??70,scores.performance??70,scores.security??70].map(Number).map(x=>Math.max(0,Math.min(100,x)));const overall=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);const report={url,data,ai:{...ai,scores:{uiux:vals[0],seo:vals[1],accessibility:vals[2],performance:vals[3],security:vals[4]}},findings:merged,overall,date:new Date().toISOString()};state.current=report;saveHistory(report);renderReport(report);showView('results')}
function saveHistory(r){let h=[];try{h=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{};h=[r,...h.filter(x=>x.url!==r.url)].slice(0,20);localStorage.setItem(HISTORY,JSON.stringify(h))}
function renderReport(r){$('#reportTitle').textContent=r.data.title||new URL(r.url).hostname;$('#reportUrl').textContent=r.url;$('#reportUrl').href=r.url;$('#overallScore').textContent=r.overall;const names=[['uiux','UI/UX'],['seo','SEO'],['accessibility','アクセシビリティ'],['performance','パフォーマンス'],['security','安全性']];$('#scoreSummary').innerHTML=names.map(([k,n])=>`<div class="score-item"><span>${n}</span><b>${r.ai.scores[k]}</b><div class="score-line"><i style="width:${r.ai.scores[k]}%"></i></div></div>`).join('');const counts={high:r.findings.filter(f=>f.severity==='high').length,medium:r.findings.filter(f=>f.severity==='medium').length,low:r.findings.filter(f=>f.severity==='low').length};$('#findingSummary').innerHTML=`<span class="pill">重大 ${counts.high}</span><span class="pill">注意 ${counts.medium}</span><span class="pill">提案 ${counts.low}</span><span class="pill">${r.findings.length}件の指摘</span>`;$('#findingCount').textContent=`${r.findings.length}件`;$('#findings').innerHTML=r.findings.map(f=>`<article class="finding"><div class="finding-top"><span class="severity ${f.severity}">${f.severity==='high'?'重大':f.severity==='medium'?'注意':'提案'}</span><span class="severity">${esc(f.category||'総合')}</span></div><h4>${esc(f.title)}</h4><p>${esc(f.description)}</p><p class="recommend"><b>改善案:</b> ${esc(f.recommendation)}</p></article>`).join('')||'<p>大きな問題は検出されませんでした。</p>';const d=r.data;$('#siteFacts').innerHTML=[['タイトル',d.title||'なし'],['HTTPS',new URL(r.url).protocol==='https:'?'有効':'なし'],['リンク',d.stats.links],['画像',d.stats.images],['フォーム',d.stats.forms],['スクリプト',d.stats.scripts],['HTMLサイズ',Math.round(d.stats.htmlBytes/1024)+' KB']].map(x=>`<div class="fact"><span>${x[0]}</span><b>${esc(String(x[1]))}</b></div>`).join('');$('#categoryScores').innerHTML=names.map(([k,n])=>`<div class="cat"><span>${n}</span><b>${r.ai.scores[k]}/100</b></div>`).join('');$('#technicalData').textContent=JSON.stringify({URL:r.url,取得日時:r.date,サイト情報:r.data.stats,見出し:r.data.headings,AI分析:r.ai},null,2)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#newScan').onclick=()=>{$('#urlInput').focus();showView('home')};$('#toggleTechnical').onclick=()=>{$('#technicalData').classList.toggle('hidden');$('#toggleTechnical').textContent=$('#technicalData').classList.contains('hidden')?'表示':'隠す'};$('#copyReport').onclick=async()=>{if(!state.current)return;const r=state.current;const text=`Web Detailed Examination\n${r.url}\n総合スコア: ${r.overall}/100\n\n${r.ai.summary||''}\n\n`+r.findings.map(f=>`[${f.severity}] ${f.title}\n${f.description}\n改善案: ${f.recommendation}`).join('\n\n');await navigator.clipboard.writeText(text);toast('レポートをコピーしました')};
function renderHistory(){let h=[];try{h=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{};$('#historyList').innerHTML=h.length?h.map((r,i)=>`<div class="history-item" data-i="${i}"><div><b>${esc(r.data?.title||new URL(r.url).hostname)}</b><small>${esc(r.url)} · ${new Date(r.date).toLocaleString('ja-JP')}</small></div><strong>${r.overall}/100</strong></div>`).join(''):'<div class="history-item"><div><b>履歴はありません</b><small>サイトを調べるとここに保存されます。</small></div></div>';$$('.history-item[data-i]').forEach(e=>e.onclick=()=>{let h=JSON.parse(localStorage.getItem(HISTORY)||'[]');state.current=h[+e.dataset.i];renderReport(state.current);showView('results')})}renderHistory();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
